// <auto-generated />
namespace Kid.English.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RestoreAbpPrefix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestoreAbpPrefix));
        
        string IMigrationMetadata.Id
        {
            get { return "201701161202097_RestoreAbpPrefix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
